# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  plan:
    # The type of runner that the job will run on
    runs-on: hashicorp/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: ls
        run: ls
      # Runs a set of commands using the runners shell
      - name: donkey tilt
        run: echo "ehehehahashdhf"
