# This is a basic workflow to help you get started with Actions

name: donkey

# Controls when the action will run. 
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  donkey:
    runs-on: ubuntu-latest
    steps:
      - name: donkey scream
        run: ls
      - uses: actions/checkout@v4
      - name: donkey scream 2
        run: ls
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
    steps:
      - name: Notify Slack Action
      - uses: ravsamhq/notify-slack-action@2.3.0
        if: ${{ always() && github.ref_name == 'main' }}
        with:
           status: ${{ job.status }}
           notify_when: "failure"
           notification_title: "{workflow} is failing"
